# Generated by Django 3.2.15 on 2022-09-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
